- name: Pure Storage FlashBlade Ansible module Demo
  hosts: localhost 
  collections:
    - purestorage.flashblade
 
  gather_facts: false
 
  tasks:
 
  - name: Create new FlashBlade FileSystem
    purefb_fs:
        fb_url: "192.168.1.11"
        api_token: "T-XxXXXxxX-XXXX-XXxX-XXXX-xxXXXXXXXxxX"
        name: "bcm-fb-nfs-mount-1"
        state: present
        size: 500G
        nfsv3: True
        nfsv4: False
        hard_limit: true
        nfs_rules: '*(rw,no_root_squash)'
        snapshot: True
